FROM browserless/chrome:latest

# Install the AWS SDK

RUN apt update \
&& apt install -y \
ca-certificates \
libnss3-tools \
ffmpeg \
aws-sdk \
&& rm -rf /var/cache/apk/*

ENV PREBOOT_CHROME=true
ENV KEEP_ALIVE=true
ENV CHROME_REFRESH_TIME=3600000
ENV MAX_QUEUE_LENGTH=20

EXPOSE 3000